/**
 * Wise King Enterprise — central product catalogue
 *
 * Load this file before js/catalogue.js or any future product/cart scripts.
 * Product visibility is controlled by `status` and `isPublic`.
 * Square checkout is intentionally not implemented in this file.
 */
(function initialiseWiseKingCatalogue(global) {
  "use strict";

  const NEEDS_CONFIRMATION = "Needs Confirmation";

  const categories = [
    {
      id: "latte-blends",
      name: "Latte Blends",
      shopLabel: "Drink",
      slug: "latte-blends",
      description: "Small-batch botanical blends for warm and iced rituals.",
      image: "",
      imageAlt: "",
      displayOrder: 10,
      isPublic: true,
    },
    {
      id: "spice-blends",
      name: "Spice Blends",
      shopLabel: "Cook",
      slug: "spice-blends",
      description: "Layered spice blends made for everyday cooking.",
      image: "",
      imageAlt: "",
      displayOrder: 20,
      isPublic: true,
    },
    {
      id: "matcha",
      name: "Matcha",
      shopLabel: "Matcha",
      slug: "matcha",
      description: "Ceremonial matcha for traditional and modern preparation.",
      image: "",
      imageAlt: "",
      displayOrder: 30,
      isPublic: true,
    },
    {
      id: "organic-powders",
      name: "Organic Powders",
      shopLabel: "Prepare",
      slug: "organic-powders",
      description: "Single-ingredient organic powders for food and drink preparation.",
      image: "",
      imageAlt: "",
      displayOrder: 40,
      isPublic: false,
    },
  ];

  const products = [
    {
      id: "golden-saffron-latte",
      name: "Golden Saffron Latte",
      sku: "WKGL001",
      price: 24.99,
      currency: "AUD",
      size: "50g",
      category: "latte-blends",
      status: "active",
      slug: "golden-saffron-latte",
      squareVariationId: NEEDS_CONFIRMATION,
      media: {
        cardImage: "NewGL.jpg",
        cardImageAlt: "Golden Saffron Latte pouch",
        galleryImages: [],
        video: "golden.MP4",
        videoPoster: "NewGL.jpg",
      },
      featured: {
        homepage: true,
        homepageOrder: 10,
        ritual: true,
      },
      isPublic: true,
      isPurchasable: true,
    },
    {
      id: "cafe-mocha",
      name: "Café Mocha",
      sku: "WKCM003",
      price: 15.99,
      currency: "AUD",
      size: "100g",
      category: "latte-blends",
      status: "active",
      slug: "cafe-mocha",
      squareVariationId: NEEDS_CONFIRMATION,
      media: {
        cardImage: "Newmocha.jpg",
        cardImageAlt: "Café Mocha pouch",
        galleryImages: [],
        video: "",
        videoPoster: "",
      },
      featured: {
        homepage: true,
        homepageOrder: 20,
        ritual: false,
      },
      isPublic: true,
      isPurchasable: true,
    },
    {
      id: "curry-coast-rub",
      name: "Curry Coast Rub",
      sku: "WKCCR002",
      price: 19.99,
      currency: "AUD",
      size: "100g",
      category: "spice-blends",
      status: "active",
      slug: "curry-coast-rub",
      squareVariationId: NEEDS_CONFIRMATION,
      media: {
        cardImage: "Newcurry.jpg",
        cardImageAlt: "Curry Coast Rub pouch",
        galleryImages: [],
        video: "",
        videoPoster: "",
      },
      featured: {
        homepage: true,
        homepageOrder: 30,
        ritual: false,
      },
      isPublic: true,
      isPurchasable: true,
    },
    {
      id: "ceremonial-matcha",
      name: "Ceremonial Matcha",
      sku: "WKCM004",
      price: 39.99,
      currency: "AUD",
      size: "30g",
      category: "matcha",
      status: "active",
      slug: "ceremonial-matcha",
      squareVariationId: NEEDS_CONFIRMATION,
      media: {
        cardImage: "NewMatcha.jpg",
        cardImageAlt: "Ceremonial Matcha pouch",
        galleryImages: [],
        video: "",
        videoPoster: "",
      },
      featured: {
        homepage: true,
        homepageOrder: 40,
        ritual: false,
      },
      isPublic: true,
      isPurchasable: true,
    },
    {
      id: "ruby-beet-latte",
      name: "Ruby Beet Latte",
      sku: NEEDS_CONFIRMATION,
      price: 15.99,
      currency: "AUD",
      size: "45g",
      category: "latte-blends",
      status: "hidden",
      slug: "ruby-beet-latte",
      squareVariationId: NEEDS_CONFIRMATION,
      packaging: "Small glass flint jar",
      media: {
        cardImage: "NewVelvet.JPG",
        cardImageAlt: "Temporary reference image for Ruby Beet Latte",
        galleryImages: [],
        video: "",
        videoPoster: "",
        temporaryReference: true,
      },
      featured: {
        homepage: false,
        homepageOrder: null,
        ritual: false,
      },
      isPublic: false,
      isPurchasable: false,
    },
    {
      id: "organic-turmeric-powder",
      name: "Organic Turmeric Powder",
      sku: NEEDS_CONFIRMATION,
      price: 9.99,
      currency: "AUD",
      size: "75g",
      category: "organic-powders",
      status: "hidden",
      slug: "organic-turmeric-powder",
      squareVariationId: NEEDS_CONFIRMATION,
      media: {
        cardImage: "",
        cardImageAlt: "",
        galleryImages: [],
        video: "",
        videoPoster: "",
      },
      featured: {
        homepage: false,
        homepageOrder: null,
        ritual: false,
      },
      isPublic: false,
      isPurchasable: false,
    },
    {
      id: "organic-beetroot-powder",
      name: "Organic Beetroot Powder",
      sku: NEEDS_CONFIRMATION,
      price: 11.99,
      currency: "AUD",
      size: "75g",
      category: "organic-powders",
      status: "hidden",
      slug: "organic-beetroot-powder",
      squareVariationId: NEEDS_CONFIRMATION,
      media: {
        cardImage: "",
        cardImageAlt: "",
        galleryImages: [],
        video: "",
        videoPoster: "",
      },
      featured: {
        homepage: false,
        homepageOrder: null,
        ritual: false,
      },
      isPublic: false,
      isPurchasable: false,
    },
    {
      id: "organic-spinach-powder",
      name: "Organic Spinach Powder",
      sku: NEEDS_CONFIRMATION,
      price: 11.99,
      currency: "AUD",
      size: "75g",
      category: "organic-powders",
      status: "hidden",
      slug: "organic-spinach-powder",
      squareVariationId: NEEDS_CONFIRMATION,
      media: {
        cardImage: "",
        cardImageAlt: "",
        galleryImages: [],
        video: "",
        videoPoster: "",
      },
      featured: {
        homepage: false,
        homepageOrder: null,
        ritual: false,
      },
      isPublic: false,
      isPurchasable: false,
    },
  ];

  global.WISE_KING_CATALOGUE = Object.freeze({
  needsConfirmation: NEEDS_CONFIRMATION,
  categories: Object.freeze(categories),
  products: Object.freeze(products),
});

global.WiseKingProducts = Object.freeze({
  products: Object.freeze(products),
});
})(globalThis);
